[toolchain]
channel = "nightly-2025-04-20" # Ensure this nightly version is recent enough
components = ["rustfmt", "clippy", "rustc-dev"] # Changed rust-src to rustc-dev
targets = ["x86_64-unknown-linux-gnu"]
