name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo fetch
      - run: cargo test --workspace --all-targets
      - run: cargo audit --deny warnings
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo fetch
      - run: cargo test --workspace
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo fetch
      - run: cargo test --workspace
